name: stylegan-pokemon
dependencies:
  - python=3.6
  - pip
  - pip:
    - Pillow
#    - tensorflow==1.14.0 # CPU support
    - tensorflow-gpu==1.14.0
    - awscli
    - matplotlib
    - requests
    - numpy
    - tqdm
